"""update business model

Revision ID: 0307922d01e5
Revises: 6326a695219d
Create Date: 2026-05-10 01:24:12.743941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0307922d01e5'
down_revision: Union[str, Sequence[str], None] = '6326a695219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('business', sa.Column('github_id', sa.String(), nullable=True))
    op.alter_column('business', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'business', ['github_id'])
    op.create_unique_constraint(None, 'business', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    op.drop_constraint(None, 'business', type_='unique')
    op.alter_column('business', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('business', 'github_id')
    op.drop_column('business', 'google_id')
    # ### end Alembic commands ###
